name: "Nicu php versions check"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Check there is no syntax errors in the project
  php-linter:
    name: Nicu check multiple php
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [5.6, 7.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: PHP syntax checker 5.6
        uses: nicumicletest/multiple-php@master
        with:
          working-directory: simple-jwt-login/
          php-version: ${{ matrix.version }}
